package core

import (
	"context"
	"errors"
	"fmt"
	"io"
	"log/slog"
	"os"
	"path/filepath"
	"runtime"
	"sort"
	"time"

	"github.com/arief-fajri/pgbase/tools/archive"
	"github.com/arief-fajri/pgbase/tools/filesystem"
	"github.com/arief-fajri/pgbase/tools/inflector"
	"github.com/arief-fajri/pgbase/tools/osutils"
	"github.com/arief-fajri/pgbase/tools/security"
)

const (
	StoreKeyActiveBackup = "@activeBackup"
)

// Backup database format identifiers (see BackupsConfig.Format).
const (
	// BackupFormatPG is the default native PostgreSQL pg_dump archive.
	BackupFormatPG = "pg"

	// BackupFormatSQLite is the legacy, engine-portable SQLite "data.db" export.
	BackupFormatSQLite = "sqlite"
)

// backupFormatOrDefault normalizes a configured backup format, defaulting an
// empty/unknown value to the native PostgreSQL format.
func backupFormatOrDefault(format string) string {
	if format == BackupFormatSQLite {
		return BackupFormatSQLite
	}
	return BackupFormatPG
}

// CreateBackup creates a new backup of the current app pb_data directory.
//
// If name is empty, it will be autogenerated.
// If backup with the same name exists, the new backup file will replace it.
//
// The native "pg" format (default) captures the database via pg_dump, which
// opens its own connection and consistent snapshot; it does NOT block writes.
// The legacy "sqlite" format reads through the app connection inside a single
// (non-blocking, MVCC) transaction. In both cases the DB dump and the storage
// archive are captured back-to-back on a best-effort basis.
//
// To safely perform the backup, it is recommended to have free disk space
// for at least 2x the size of the pb_data directory.
//
// By default backups are stored in pb_data/backups
// (the backups directory itself is excluded from the generated backup).
//
// When using S3 storage for the uploaded collection files, you have to
// take care manually to backup those since they are not part of the pb_data.
//
// Backups can be stored on S3 if it is configured in app.Settings().Backups.
func (app *BaseApp) CreateBackup(ctx context.Context, name string) error {
	if app.Store().Has(StoreKeyActiveBackup) {
		return errors.New("try again later - another backup/restore operation has already been started")
	}

	app.Store().Set(StoreKeyActiveBackup, name)
	defer app.Store().Remove(StoreKeyActiveBackup)

	event := new(BackupEvent)
	event.App = app
	event.Context = ctx
	event.Name = name
	// default root dir entries to exclude from the backup generation
	event.Exclude = []string{
		LocalBackupsDirName,
		LocalTempDirName,
		LocalNotifyDirName,
		LocalAutocertCacheDirName,
		lostFoundDirName,
	}

	return app.OnBackupCreate().Trigger(event, func(e *BackupEvent) error {
		// generate a default name if missing
		if e.Name == "" {
			e.Name = generateBackupName(e.App, "pb_backup_")
		}

		// make sure that the special temp directory exists
		// note: it needs to be inside the current pb_data to avoid "cross-device link" errors
		localTempDir := filepath.Join(e.App.DataDir(), LocalTempDirName)
		if err := os.MkdirAll(localTempDir, os.ModePerm); err != nil {
			return fmt.Errorf("failed to create a temp dir: %w", err)
		}

		// Bundle a full database dump at the pb_data root so the produced archive
		// captures the whole database (not just the storage filesystem), then
		// archive pb_data into a temp file. The dump format is selected by the
		// Backups.Format setting:
		//   - "pg" (default): a native, full-fidelity pg_dump archive
		//     ("pgdata.dump") restored via pg_restore.
		//   - "sqlite" (legacy/opt-in): a portable, v0.23-format SQLite "data.db"
		//     that the cross-engine importer and older tooling can read.
		// The restore path auto-detects which one is present.
		//
		// NB: the DB dump and the storage archive are captured back-to-back but
		// are NOT a single atomic snapshot (pg_dump uses its own connection and
		// snapshot; the filesystem archive is separate) - consistency is
		// best-effort, same as before.
		// ---
		tempPath := filepath.Join(localTempDir, "pb_backup_"+security.PseudorandomString(6))

		format := backupFormatOrDefault(e.App.Settings().Backups.Format)

		dbDumpName := pgBackupDumpName
		if format == BackupFormatSQLite {
			dbDumpName = sqliteBackupDBName
		}
		dbDumpPath := filepath.Join(e.App.DataDir(), dbDumpName)
		defer os.Remove(dbDumpPath)

		if format == BackupFormatSQLite {
			// The legacy SQLite export reads many tables through the app
			// connection, so run it inside a single transaction to keep those
			// reads best-effort consistent. NB: on PostgreSQL this does NOT block
			// other writes (MVCC) - it only groups the export's own reads.
			exportErr := e.App.RunInTransaction(func(txApp App) error {
				bapp, ok := txApp.(*BaseApp)
				if !ok {
					return errors.New("unexpected transaction app type for the database export")
				}
				if err := bapp.ExportToSQLiteFile(e.Context, dbDumpPath); err != nil {
					return fmt.Errorf("failed to export the database snapshot: %w", err)
				}
				return nil
			})
			if exportErr != nil {
				return exportErr
			}
		} else {
			// pg_dump runs as an external process with its own libpq connection
			// and its own consistent snapshot, so it must NOT be wrapped in
			// app.RunInTransaction: a long-running idle transaction here would add
			// no consistency for pg_dump and would only pin the xmin horizon
			// (stalling autovacuum) and hold a data-pool connection for the whole
			// duration of the dump.
			if err := app.ExportToPGDump(e.Context, dbDumpPath); err != nil {
				return fmt.Errorf("failed to export the database snapshot: %w", err)
			}
		}

		// archive pb_data (including the freshly written DB dump). This is a
		// filesystem-only operation and needs no DB transaction.
		if err := archive.Create(e.App.DataDir(), tempPath, e.Exclude...); err != nil {
			return err
		}
		defer os.Remove(tempPath)

		// persist the backup in the backups filesystem
		// ---
		fsys, err := e.App.NewBackupsFilesystem()
		if err != nil {
			return err
		}
		defer fsys.Close()

		fsys.SetContext(e.Context)

		file, err := filesystem.NewFileFromPath(tempPath)
		if err != nil {
			return err
		}
		file.OriginalName = e.Name
		file.Name = file.OriginalName

		if err := fsys.UploadFile(file, file.Name); err != nil {
			return err
		}

		return nil
	})
}

// RestoreBackup restores the backup with the specified name and restarts
// the current running application process.
//
// NB! This feature is experimental and currently is expected to work only on UNIX based systems.
//
// To safely perform the restore it is recommended to have free disk space
// for at least 2x the size of the restored pb_data backup.
//
// The performed steps are:
//
//  1. Download the backup with the specified name in a temp location
//     (this is in case of S3; otherwise it creates a temp copy of the zip)
//
//  2. Extract the backup in a temp directory inside the app "pb_data"
//     (eg. "pb_data/.pb_temp_to_delete/pb_restore").
//
//  3. Move the current app "pb_data" content (excluding the local backups and the special temp dir)
//     under another temp sub dir that will be deleted on the next app start up
//     (eg. "pb_data/.pb_temp_to_delete/old_pb_data").
//     This is because on some environments it may not be allowed
//     to delete the currently open "pb_data" files.
//
//  4. Move the extracted dir content to the app "pb_data".
//
//  5. Restart the app (on successful app bootstrap it will also remove the old pb_data).
//
// If a failure occur during the restore process the dir changes are reverted.
// If for whatever reason the revert is not possible, it panics.
//
// Note that if your pb_data has custom network mounts as subdirectories, then
// it is possible the restore to fail during the `os.Rename` operations
// (see https://github.com/arief-fajri/pgbase/issues/4647).
func (app *BaseApp) RestoreBackup(ctx context.Context, name string) error {
	return app.restoreBackup(ctx, name, true)
}

// RestoreBackupWithoutRestart is like [BaseApp.RestoreBackup] but it does NOT
// restart the application process after a successful restore.
//
// It is intended for offline, one-shot restores (e.g. the "restore" CLI
// command) where restarting via execve would simply re-run the same command
// and loop. After it returns, (re)start the app normally to load the restored
// data.
func (app *BaseApp) RestoreBackupWithoutRestart(ctx context.Context, name string) error {
	return app.restoreBackup(ctx, name, false)
}

// restoreBackup performs the actual backup restore. When restartAfter is true
// the app process is restarted (execve) on success; otherwise it returns as
// soon as the data has been restored, leaving the current process untouched.
func (app *BaseApp) restoreBackup(ctx context.Context, name string, restartAfter bool) error {
	if app.Store().Has(StoreKeyActiveBackup) {
		return errors.New("try again later - another backup/restore operation has already been started")
	}

	app.Store().Set(StoreKeyActiveBackup, name)
	defer app.Store().Remove(StoreKeyActiveBackup)

	event := new(BackupEvent)
	event.App = app
	event.Context = ctx
	event.Name = name
	// default root dir entries to exclude from the backup restore
	event.Exclude = []string{LocalBackupsDirName, LocalTempDirName, LocalAutocertCacheDirName, lostFoundDirName}

	return app.OnBackupRestore().Trigger(event, func(e *BackupEvent) error {
		if runtime.GOOS == "windows" {
			return errors.New("restore is not supported on Windows")
		}

		// make sure that the special temp directory exists
		// note: it needs to be inside the current pb_data to avoid "cross-device link" errors
		localTempDir := filepath.Join(e.App.DataDir(), LocalTempDirName)
		if err := os.MkdirAll(localTempDir, os.ModePerm); err != nil {
			return fmt.Errorf("failed to create a temp dir: %w", err)
		}

		fsys, err := e.App.NewBackupsFilesystem()
		if err != nil {
			return err
		}
		defer fsys.Close()

		fsys.SetContext(e.Context)

		if ok, _ := fsys.Exists(name); !ok {
			return fmt.Errorf("missing or invalid backup file %q to restore", name)
		}

		extractedDataDir := filepath.Join(localTempDir, "pb_restore_"+security.PseudorandomString(8))
		defer os.RemoveAll(extractedDataDir)

		// extract the zip
		if e.App.Settings().Backups.S3.Enabled {
			br, err := fsys.GetReader(name)
			if err != nil {
				return err
			}
			defer br.Close()

			// create a temp zip file from the blob.Reader and try to extract it
			tempZip, err := os.CreateTemp(localTempDir, "pb_restore_zip")
			if err != nil {
				return err
			}
			defer os.Remove(tempZip.Name())
			defer tempZip.Close() // note: this technically shouldn't be necessary but it is here to workaround platforms discrepancies

			_, err = io.Copy(tempZip, br)
			if err != nil {
				return err
			}

			err = archive.Extract(tempZip.Name(), extractedDataDir)
			if err != nil {
				return err
			}

			// remove the temp zip file since we no longer need it
			// (this is in case the app restarts and the defer calls are not called)
			_ = tempZip.Close()
			err = os.Remove(tempZip.Name())
			if err != nil {
				e.App.Logger().Warn(
					"[RestoreBackup] Failed to remove the temp zip backup file",
					slog.String("file", tempZip.Name()),
					slog.String("error", err.Error()),
				)
			}
		} else {
			// manually construct the local path to avoid creating a copy of the zip file
			// since the blob reader currently doesn't implement ReaderAt
			zipPath := filepath.Join(e.App.DataDir(), LocalBackupsDirName, filepath.Base(name))

			err = archive.Extract(zipPath, extractedDataDir)
			if err != nil {
				return err
			}
		}

		// ensure that the extracted backup has content (storage dir, etc.)
		entries, readErr := os.ReadDir(extractedDataDir)
		if readErr != nil || len(entries) == 0 {
			return fmt.Errorf("the backup archive is empty or invalid: %w", readErr)
		}

		// A native PostgreSQL backup bundles the whole database as a single
		// custom-format pg_dump archive ("pgdata.dump"). Detect it first and
		// restore it via pg_restore into the live database, then restart so the
		// collection cache and settings are reloaded from the restored data.
		if _, statErr := os.Stat(filepath.Join(extractedDataDir, pgBackupDumpName)); statErr == nil {
			if importErr := app.ImportFromPGDump(e.Context, extractedDataDir); importErr != nil {
				return fmt.Errorf("failed to import the PostgreSQL backup: %w", importErr)
			}

			if !restartAfter {
				return nil
			}

			// restart so the collection cache and settings are reloaded from
			// the freshly restored data
			if err := e.App.Restart(); err != nil {
				return fmt.Errorf("failed to restart the app process after the PostgreSQL import: %w", err)
			}

			return nil
		}

		// A legacy SQLite-based PocketBase backup bundles its whole database as
		// a single "data.db" file. Since this fork stores everything in a
		// separate PostgreSQL server, the plain pb_data file-swap below would
		// only copy that file as dead weight and never touch Postgres. Detect
		// it and branch to a dedicated importer that converts the SQLite data
		// into the current Postgres-backed app instead.
		if _, statErr := os.Stat(filepath.Join(extractedDataDir, sqliteBackupDBName)); statErr == nil {
			if importErr := app.ImportFromSQLiteDir(e.Context, extractedDataDir); importErr != nil {
				return fmt.Errorf("failed to import the legacy SQLite backup: %w", importErr)
			}

			if !restartAfter {
				return nil
			}

			// restart so the collection cache and settings are reloaded from
			// the freshly imported data
			if err := e.App.Restart(); err != nil {
				return fmt.Errorf("failed to restart the app process after the SQLite import: %w", err)
			}

			return nil
		}

		oldTempDataDir := filepath.Join(localTempDir, "old_pb_data_"+security.PseudorandomString(8))

		replaceErr := e.App.RunInTransaction(func(txApp App) error {
			return txApp.AuxRunInTransaction(func(txApp App) error {
				// move the current pb_data content to a special temp location
				// that will hold the old data between dirs replace
				// (the temp dir will be automatically removed on the next app start)
				if err := osutils.MoveDirContent(txApp.DataDir(), oldTempDataDir, e.Exclude...); err != nil {
					return fmt.Errorf("failed to move the current pb_data content to a temp location: %w", err)
				}

				// move the extracted archive content to the app's pb_data
				if err := osutils.MoveDirContent(extractedDataDir, txApp.DataDir(), e.Exclude...); err != nil {
					return fmt.Errorf("failed to move the extracted archive content to pb_data: %w", err)
				}

				return nil
			})
		})
		if replaceErr != nil {
			return replaceErr
		}

		if !restartAfter {
			// offline restore (e.g. CLI): the pb_data swap is complete and the
			// old pb_data will be removed on the next app bootstrap; there is
			// nothing to restart here.
			return nil
		}

		revertDataDirChanges := func() error {
			return e.App.RunInTransaction(func(txApp App) error {
				return txApp.AuxRunInTransaction(func(txApp App) error {
					if err := osutils.MoveDirContent(txApp.DataDir(), extractedDataDir, e.Exclude...); err != nil {
						return fmt.Errorf("failed to revert the extracted dir change: %w", err)
					}

					if err := osutils.MoveDirContent(oldTempDataDir, txApp.DataDir(), e.Exclude...); err != nil {
						return fmt.Errorf("failed to revert old pb_data dir change: %w", err)
					}

					return nil
				})
			})
		}

		// restart the app
		if err := e.App.Restart(); err != nil {
			if revertErr := revertDataDirChanges(); revertErr != nil {
				panic(revertErr)
			}

			return fmt.Errorf("failed to restart the app process: %w", err)
		}

		return nil
	})
}

// registerAutobackupHooks registers the autobackup app serve hooks.
func (app *BaseApp) registerAutobackupHooks() {
	const jobId = "__pbAutoBackup__"

	loadJob := func() {
		rawSchedule := app.Settings().Backups.Cron
		if rawSchedule == "" {
			app.Cron().Remove(jobId)
			return
		}

		app.Cron().Add(jobId, rawSchedule, func() {
			const autoPrefix = "@auto_pb_backup_"

			name := generateBackupName(app, autoPrefix)

			if err := app.CreateBackup(context.Background(), name); err != nil {
				app.Logger().Error(
					"[Backup cron] Failed to create backup",
					slog.String("name", name),
					slog.String("error", err.Error()),
				)

				alertError := sendSystemAlertToAllSuperusers(
					app,
					"Autobackup failure",
					"Failed to create/upload automated backup. Raw error:\n"+err.Error(),
				)
				if alertError != nil {
					app.Logger().Warn(
						"[Backup cron] Failed to send backup error alerts",
						slog.String("name", name),
						slog.String("error", alertError.Error()),
					)
				}
			}

			maxKeep := app.Settings().Backups.CronMaxKeep

			if maxKeep == 0 {
				return // no explicit limit
			}

			fsys, err := app.NewBackupsFilesystem()
			if err != nil {
				app.Logger().Error(
					"[Backup cron] Failed to initialize the backup filesystem",
					slog.String("error", err.Error()),
				)
				return
			}
			defer fsys.Close()

			files, err := fsys.List(autoPrefix)
			if err != nil {
				app.Logger().Error(
					"[Backup cron] Failed to list autogenerated backups",
					slog.String("error", err.Error()),
				)
				return
			}

			if maxKeep >= len(files) {
				return // nothing to remove
			}

			// sort desc
			sort.Slice(files, func(i, j int) bool {
				return files[i].ModTime.After(files[j].ModTime)
			})

			// keep only the most recent n auto backup files
			toRemove := files[maxKeep:]

			for _, f := range toRemove {
				if err := fsys.Delete(f.Key); err != nil {
					app.Logger().Error(
						"[Backup cron] Failed to remove old autogenerated backup",
						slog.String("key", f.Key),
						slog.String("error", err.Error()),
					)
				}
			}
		})
	}

	app.OnBootstrap().BindFunc(func(e *BootstrapEvent) error {
		if err := e.Next(); err != nil {
			return err
		}

		loadJob()

		return nil
	})

	app.OnSettingsReload().BindFunc(func(e *SettingsReloadEvent) error {
		if err := e.Next(); err != nil {
			return err
		}

		loadJob()

		return nil
	})
}

func generateBackupName(app App, prefix string) string {
	appName := inflector.Snakecase(app.Settings().Meta.AppName)
	if len(appName) > 50 {
		appName = appName[:50]
	}

	return fmt.Sprintf(
		"%s%s_%s.zip",
		prefix,
		appName,
		time.Now().UTC().Format("20060102150405"),
	)
}
