package core

import (
	"cmp"
	"context"
	"database/sql"
	"encoding/json"
	"errors"
	"fmt"
	"slices"

	validation "github.com/pocketbase/ozzo-validation/v4"
	"github.com/spf13/cast"
)

// ImportCollectionsByMarshaledJSON is the same as [ImportCollections]
// but accept marshaled json array as import data (usually used for the autogenerated snapshots).
func (app *BaseApp) ImportCollectionsByMarshaledJSON(rawSliceOfMaps []byte, deleteMissing bool) error {
	data := []map[string]any{}

	err := json.Unmarshal(rawSliceOfMaps, &data)
	if err != nil {
		return err
	}

	return app.ImportCollections(data, deleteMissing)
}

// ImportCollections imports the provided collections data in a single transaction.
//
// For existing matching collections, the imported data is unmarshaled on top of the existing model.
//
// NB! If deleteMissing is true, ALL NON-SYSTEM COLLECTIONS AND SCHEMA FIELDS,
// that are not present in the imported configuration, WILL BE DELETED
// (this includes their related records data).
func (app *BaseApp) ImportCollections(toImport []map[string]any, deleteMissing bool) error {
	if len(toImport) == 0 {
		// prevent accidentally deleting all collections
		return errors.New("no collections to import")
	}

	importedCollections := make([]*Collection, len(toImport))
	mappedImported := make(map[string]*Collection, len(toImport))

	// normalize imported collections data to ensure that all
	// collection fields are present and properly initialized
	for i, data := range toImport {
		var imported *Collection

		identifier := cast.ToString(data["id"])
		if identifier == "" {
			identifier = cast.ToString(data["name"])
		}

		existing, err := app.FindCollectionByNameOrId(identifier)
		if err != nil && !errors.Is(err, sql.ErrNoRows) {
			return err
		}

		if existing != nil {
			// refetch for deep copy
			imported, err = app.FindCollectionByNameOrId(existing.Id)
			if err != nil {
				return err
			}

			// ensure that the fields will be cleared
			if data["fields"] == nil && deleteMissing {
				data["fields"] = []map[string]any{}
			}

			rawData, err := json.Marshal(data)
			if err != nil {
				return err
			}

			// load the imported data
			err = json.Unmarshal(rawData, imported)
			if err != nil {
				return err
			}

			// extend with the existing fields if necessary
			for _, f := range existing.Fields {
				if !f.GetSystem() && deleteMissing {
					continue
				}
				if imported.Fields.GetById(f.GetId()) == nil {
					// replace with the existing id to prevent accidental column deletion
					// since otherwise the imported field will be treated as a new one
					found := imported.Fields.GetByName(f.GetName())
					if found != nil && found.Type() == f.Type() {
						found.SetId(f.GetId())
					}
					imported.Fields.Add(f)
				}
			}
		} else {
			imported = &Collection{}

			rawData, err := json.Marshal(data)
			if err != nil {
				return err
			}

			// load the imported data
			err = json.Unmarshal(rawData, imported)
			if err != nil {
				return err
			}
		}

		imported.IntegrityChecks(false)

		importedCollections[i] = imported
		mappedImported[imported.Id] = imported
	}

	// reorder views last since the view query could depend on some of the other collections
	slices.SortStableFunc(importedCollections, func(a, b *Collection) int {
		cmpA := -1
		if a.IsView() {
			cmpA = 1
		}

		cmpB := -1
		if b.IsView() {
			cmpB = 1
		}

		res := cmp.Compare(cmpA, cmpB)
		if res == 0 {
			res = a.Created.Compare(b.Created)
			if res == 0 {
				res = a.Updated.Compare(b.Updated)
			}
		}
		return res
	})

	return app.RunInTransaction(func(txApp App) error {
		existingCollections := []*Collection{}
		if err := txApp.CollectionQuery().OrderBy("updated ASC").All(&existingCollections); err != nil {
			return err
		}
		mappedExisting := make(map[string]*Collection, len(existingCollections))
		for _, existing := range existingCollections {
			existing.IntegrityChecks(false)
			mappedExisting[existing.Id] = existing
		}

		// delete old collections not available in the new configuration
		// (before saving the imports in case a deleted collection name is being reused)
		if deleteMissing {
				missing := make(map[string]*Collection)
				for _, existing := range existingCollections {
					if mappedImported[existing.Id] == nil && !existing.System {
						missing[existing.Id] = existing
					}
				}

				// Delete views first, then relation dependents before their targets.
				// This keeps record cascade checks from blocking the transaction when
				// deleteMissing removes an entire related collection graph.
				dependents := make(map[string][]*Collection)
				for _, existing := range missing {
					if existing.IsView() {
						continue
					}
					for _, rawField := range existing.Fields {
						field, ok := rawField.(*RelationField)
						if !ok || field.CollectionId == existing.Id || missing[field.CollectionId] == nil {
							continue
						}
						dependents[field.CollectionId] = append(dependents[field.CollectionId], existing)
					}
				}

				deleteOrder := make([]*Collection, 0, len(missing))
				visited := make(map[string]bool, len(missing))
				var visit func(*Collection)
				visit = func(collection *Collection) {
					if collection == nil || visited[collection.Id] {
						return
					}
					visited[collection.Id] = true
					for _, dependent := range dependents[collection.Id] {
						visit(dependent)
					}
					deleteOrder = append(deleteOrder, collection)
				}

				for _, existing := range existingCollections {
					if existing.IsView() && missing[existing.Id] != nil {
						visit(existing)
					}
				}
				for _, existing := range existingCollections {
					if !existing.IsView() && missing[existing.Id] != nil {
						visit(existing)
					}
				}

				for _, existing := range deleteOrder {
					if err := txApp.Delete(existing); err != nil {
						return err
					}
				}
		}

		// PGB-L02: validate collection/field names BEFORE the DDL loop so a
		// crafted name (quotes, spaces, etc.) can never reach the identifier
		// interpolation in CreateTable/ALTER, even though import is
		// superuser-only and the whole operation runs in a transaction.
		for _, imported := range importedCollections {
			if !collectionNameRegex.MatchString(imported.Name) {
				return fmt.Errorf(
					"invalid collection name %q in import data (allowed: %s)",
					imported.Name,
					collectionNameRegex.String(),
				)
			}

			for _, f := range imported.Fields {
				if !fieldNameRegex.MatchString(f.GetName()) {
					return fmt.Errorf(
						"invalid field name %q in collection %q import data (allowed: %s)",
						f.GetName(),
						imported.Name,
						fieldNameRegex.String(),
					)
				}
			}
		}

		// upsert imported collections
		for _, imported := range importedCollections {
			if err := txApp.SaveNoValidate(imported); err != nil {
				return fmt.Errorf("failed to save collection %q: %w", imported.Name, err)
			}
		}

		// run validations
		for _, imported := range importedCollections {
			original := mappedExisting[imported.Id]
			if original == nil {
				original = imported
			}

			validator := newCollectionValidator(
				context.Background(),
				txApp,
				imported,
				original,
			)
			if err := validator.run(); err != nil {
				// serialize the validation error(s)
				serializedErr, _ := json.MarshalIndent(err, "", "  ")

				return validation.Errors{"collections": validation.NewError(
					"validation_collections_import_failure",
					fmt.Sprintf("Data validations failed for collection %q (%s):\n%s", imported.Name, imported.Id, serializedErr),
				)}
			}
		}

		return nil
	})
}
