package cmd

import (
	"errors"
	"fmt"

	"github.com/fatih/color"
	"github.com/arief-fajri/pgbase/core"
	"github.com/spf13/cobra"
)

// NewBackupCommand creates and returns new command for creating app data backups.
func NewBackupCommand(app core.App) *cobra.Command {
	var format string

	command := &cobra.Command{
		Use:   "backup [name]",
		Short: "Creates a new app data backup",
		Long: `Creates a new app data backup.

If no name is provided, one will be autogenerated.
The backup bundles a full database dump alongside the storage files.

The database dump format defaults to the configured Backups.Format setting
(native PostgreSQL "pg" unless changed) and can be overridden for this run
with the --format flag.`,
		Args:         cobra.MaximumNArgs(1),
		SilenceUsage: true,
		RunE: func(command *cobra.Command, args []string) error {
			var name string
			if len(args) > 0 {
				name = args[0]
			}

			// optionally override the configured backup format for this run only
			// (in-memory, not persisted)
			if format != "" {
				if format != core.BackupFormatPG && format != core.BackupFormatSQLite {
					return fmt.Errorf(
						"invalid --format %q (must be %q or %q)",
						format, core.BackupFormatPG, core.BackupFormatSQLite,
					)
				}

				original := app.Settings().Backups.Format
				app.Settings().Backups.Format = format
				defer func() {
					app.Settings().Backups.Format = original
				}()
			}

			if err := app.CreateBackup(command.Context(), name); err != nil {
				return fmt.Errorf("failed to create backup: %w", err)
			}

			if name != "" {
				color.Green("Successfully created backup %q!", name)
			} else {
				color.Green("Successfully created backup!")
			}

			return nil
		},
	}

	command.PersistentFlags().StringVar(
		&format,
		"format",
		"",
		`database dump format: "pg" (native PostgreSQL, default) or "sqlite" (portable, legacy)`,
	)

	return command
}

// NewRestoreCommand creates and returns new command for restoring an app data backup.
func NewRestoreCommand(app core.App) *cobra.Command {
	command := &cobra.Command{
		Use:   "restore [name]",
		Short: "Restores an app data backup by name",
		Long: `Restores the app data backup with the specified name.

Unlike the dashboard/API restore, this command performs an offline restore and
does NOT restart the process, so it is safe to run while the server is stopped.
(Re)start the application afterwards to load the restored data.

It auto-detects the bundled database dump format (native PostgreSQL or the
legacy portable SQLite) and imports it into the current database.`,
		Args:         cobra.ExactArgs(1),
		SilenceUsage: true,
		RunE: func(command *cobra.Command, args []string) error {
			name := args[0]
			if name == "" {
				return errors.New("missing backup name argument")
			}

			if err := app.RestoreBackupWithoutRestart(command.Context(), name); err != nil {
				return fmt.Errorf("failed to restore backup: %w", err)
			}

			color.Green("Successfully restored backup %q!", name)
			color.Yellow("(Re)start the application to load the restored data.")

			return nil
		},
	}

	return command
}
